code --install-extension be5invis.toml
code --install-extension DavidAnson.vscode-markdownlint
code --install-extension dbaeumer.vscode-eslint
code --install-extension drKnoxy.eslint-disable-snippets
code --install-extension eamodio.gitlens
code --install-extension ms-python.python
code --install-extension plex.vscode-regolint
code --install-extension redhat.vscode-yaml
code --install-extension rogalmic.bash-debug
code --install-extension samverschueren.final-newline
code --install-extension timonwong.shellcheck
code --install-extension tsandall.opa
