#!/bin/bash
code --install-extension 42Crunch.vscode-openapi
code --install-extension be5invis.toml
code --install-extension DavidAnson.vscode-markdownlint
code --install-extension dbaeumer.vscode-eslint
code --install-extension drKnoxy.eslint-disable-snippets
code --install-extension eamodio.gitlens
code --install-extension golang.go
code --install-extension jetmartin.bats
code --install-extension hashicorp.terraform
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-kubernetes-tools.vscode-kubernetes-tools
code --install-extension ms-python.isort
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-toolsai.jupyter
code --install-extension ms-toolsai.jupyter-keymap
code --install-extension ms-toolsai.jupyter-renderers
code --install-extension ms-toolsai.vscode-jupyter-cell-tags
code --install-extension ms-toolsai.vscode-jupyter-slideshow
code --install-extension ms-vscode-remote.remote-containers
code --install-extension plex.vscode-regolint
code --install-extension redhat.vscode-yaml
code --install-extension rogalmic.bash-debug
code --install-extension samverschueren.final-newline
code --install-extension svelte.svelte-vscode
code --install-extension timonwong.shellcheck
code --install-extension tsandall.opa
code --install-extension zxh404.vscode-proto3
